baseurl         = "http://agileopenfrance.com/"
theme           = "gohugo-theme-ananke"
languageCode    = "fr"
title           = "Agile Open France"
paginate        = 4
publishDir      = "docs"
disqusShortname = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
