baseurl         = "https://agileopenfrance.com/"
theme           = "gohugo-theme-ananke"
languageCode    = "fr"
title           = "Agile Open France"
paginate        = 4
publishDir      = "docs"
disqusShortname = ""
enableRobotsTXT = true
buildFuture     = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
  
[markup.goldmark.renderer]
unsafe= true